sudo: false
language: go
go:
  - 1.13.x
  - master
env:
  - GO111MODULE=on
script:
  - make build-all
notification:
  email: false
deploy:
  provider: releases
  api_key: 
    secure: 15d24c7efe19342581a5f3eb7d6949f64772ff67
  file:
    -  app/lyrics
    -  app/lyrics_osx
  skip_cleanup: true
  on:
    tags: true

