sudo: false
language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on
script:
  - make build-all
notification:
  email: false
deploy:
  provider: releases
  api_key: 
    secure: ac37caf518651f15528e67dd195f6f69dd4c5d48
  file:
    -  app/lyrics
    -  app/lyrics_osx
  skip_cleanup: true
  on:
    tags: true

