sudo: false
language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on
script:
  - make build-all
notification:
  email: false
deploy:
  provider: releases
  api_key: 
    secure: 32387a2496c2b27093b9f273017c2b3029877aa5
  file:
    -  app/lyrics
    -  app/lyrics_osx
  skip_cleanup: true
  on:
    tags: true

